server:
  port: ${PORT:8864}
message: Configuracion de Producto en el servidor levantado!
spring:
datasource:
driver-class-name: com.mysql.cj.jdbc.Driver
password: 123456789
url: jubc:mysql://localhost:3306/crudcloud?serverTimezone=UTC
username: root
jpa:
  hiperbanate:
    ddl-auto: update
    detabase-platform: org.hibernate.dialect.MySQLDialect
cloud:
  config:
    url: http://localhost:8860
